// Значки ресурсов сохранены локально и показываются только в выбранном рецепте.
export const resourceIcons: Record<string, string> = {
  "Алтей": "/images/resources/grasses-12.gif",
  "Ананас": "/images/resources/45.png",
  "Базилик": "/images/resources/52.png",
  "Баклажаны": "/images/resources/47.png",
  "Белладонна": "/images/resources/grasses-08.gif",
  "Бечевка": "/images/resources/it-r-string.png",
  "Большая руна брони": "/images/resources/22-73-01.gif",
  "Большая руна жизни": "/images/resources/22-71-01.gif",
  "Большая руна меткости": "/images/resources/22-74-01.gif",
  "Большая руна силы": "/images/resources/22-72-01.gif",
  "Брусника": "/images/resources/49.png",
  "Буряк": "/images/resources/32.png",
  "Ведьмина трава": "/images/resources/grasses-07.gif",
  "Великая руна брони": "/images/resources/22-77-01.gif",
  "Великая руна жизни": "/images/resources/22-75-01.gif",
  "Великая руна меткости": "/images/resources/22-78-01.gif",
  "Великая руна силы": "/images/resources/22-76-01.gif",
  "Виноград": "/images/resources/12.png",
  "Гранат": "/images/resources/25.png",
  "Груша": "/images/resources/5.png",
  "Дуб": "/images/resources/it-r-wood.gif",
  "Душа повелителя": "/images/resources/22-310-01.gif",
  "Железная руда": "/images/resources/it-r-ore.gif",
  "Железное дерево": "/images/resources/it-r-stonewood.png",
  "Зверобой": "/images/resources/27.png",
  "Зверобой лесной": "/images/resources/grasses-00.png",
  "Золотое сердце": "/images/resources/19-28-00.gif",
  "Имобиус": "/images/resources/grasses-11.gif",
  "Капля крови": "/images/resources/kr.gif",
  "Капуста": "/images/resources/34.png",
  "Картошка": "/images/resources/31.png",
  "Кожа": "/images/resources/it-r-skin.png",
  "Кокос": "/images/resources/54.png",
  "Корень мандрагоры": "/images/resources/grasses-06.gif",
  "Кориандр": "/images/resources/grasses-10.gif",
  "Кости": "/images/resources/it-r-bones.png",
  "Кровавое сердце": "/images/resources/19-28-02.gif",
  "Малахитовое сердце": "/images/resources/19-28-01.gif",
  "Малая руна брони": "/images/resources/22-65-01.gif",
  "Малая руна жизни": "/images/resources/22-63-01.gif",
  "Малая руна меткости": "/images/resources/22-66-01.gif",
  "Малая руна силы": "/images/resources/22-64-01.gif",
  "Медь": "/images/resources/it-r-copper.png",
  "Миндаль": "/images/resources/24.png",
  "Мифрильное сердце": "/images/resources/19-28-03.gif",
  "Мята": "/images/resources/51.png",
  "Нитка": "/images/resources/it-r-cotton.png",
  "Папоротник": "/images/resources/grasses-01.gif",
  "Растение богов": "/images/resources/19.png",
  "Растительное мясо": "/images/resources/48.png",
  "Рецепт лабиринта": "/images/resources/19-27-01.gif",
  "Розмарин": "/images/resources/grasses-09.gif",
  "Руна брони": "/images/resources/r-03-02.gif",
  "Руна жизни": "/images/resources/r-01-02.gif",
  "Руна меткости": "/images/resources/r-04-02.gif",
  "Руна силы": "/images/resources/r-02-02.gif",
  "Сапфир": "/images/resources/it-r-saphir.png",
  "Серебро": "/images/resources/it-r-silver.png",
  "Титаниус": "/images/resources/grasses-13.gif",
  "Ткань": "/images/resources/it-r-cloth.png",
  "Топаз": "/images/resources/it-r-topaz.png",
  "Уголь": "/images/resources/it-r-coal.gif",
  "Фасоль": "/images/resources/50.png",
  "Финики": "/images/resources/56.png",
  "Чернокорень": "/images/resources/grasses-03.gif",
  "Чертополох": "/images/resources/grasses-04.gif",
  "Чеснок": "/images/resources/2.png",
  "Чили": "/images/resources/22.png",
  "Шкура волка": "/images/resources/skins-wolf.gif",
  "Шкура зайца": "/images/resources/skins-zajets.gif",
  "Шкура кабана": "/images/resources/skins-vepr.gif",
  "Шкура медведя": "/images/resources/skins-bear.gif",
  "Яблоко": "/images/resources/41.png"
};
