"use client";
import { useMemo, useState } from "react";
import Link from "next/link";
import styles from "../collection-pages.module.css";
type Player={cuid:string;nick:string;level?:number;clanId?:string;clanName?:string;profileUrl?:string;marriagePartner?:string;marriageSince?:string};
type Couple={a:Player;b?:Player;partnerName:string;since:string};
export default function CouplesClient({players,smileCounts,itemCounts}:{players:Player[];smileCounts:Record<string,number>;itemCounts:Record<string,number>}){
 const [query,setQuery]=useState(""); const [sort,setSort]=useState<"date"|"names">("date");
 const couples=useMemo(()=>{const byName=new Map(players.map(p=>[p.nick.toLocaleLowerCase("ru"),p]));const used=new Set<string>();const list:Couple[]=[];for(const p of players){const partner=(p.marriagePartner||"").trim();if(!partner)continue;const other=byName.get(partner.toLocaleLowerCase("ru"));const key=[p.nick.toLocaleLowerCase("ru"),partner.toLocaleLowerCase("ru")].sort().join("|");if(used.has(key))continue;used.add(key);list.push({a:p,b:other,partnerName:other?.nick||partner,since:p.marriageSince||other?.marriageSince||""});}const q=query.trim().toLocaleLowerCase("ru");return list.filter(c=>!q||c.a.nick.toLocaleLowerCase("ru").includes(q)||c.partnerName.toLocaleLowerCase("ru").includes(q)).sort((x,y)=>sort==="names"?x.a.nick.localeCompare(y.a.nick,"ru"):(parseDate(x.since)-parseDate(y.since))||x.a.nick.localeCompare(y.a.nick,"ru"));},[players,query,sort]);
 return <main className={styles.page}><section className={styles.shell}><header className={styles.hero}><div className={styles.heroIcon}>💍</div><div><p className={styles.eyebrow}>Истории, которые начались в игре</p><h1>Семейные пары</h1><p>Кто с кем, с какой даты и какие коллекции успела собрать каждая пара.</p></div></header><div className={styles.stats}><span><b>{couples.length}</b> семейных пар</span><span>Данные берём прямо из профилей персонажей</span></div><div className={styles.controls}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Найти кого-нибудь из пары…"/><div><button className={sort==="date"?styles.active:""} onClick={()=>setSort("date")}>Дольше вместе</button><button className={sort==="names"?styles.active:""} onClick={()=>setSort("names")}>По именам</button></div></div><div className={styles.coupleGrid}>{couples.map(c=><article className={styles.couple} key={`${c.a.nick}-${c.partnerName}`}><div className={styles.heart}>♥</div><div className={styles.people}><Person p={c.a} smiles={smileCounts[c.a.nick.toLocaleLowerCase("ru")]||0} items={itemCounts[c.a.nick.toLocaleLowerCase("ru")]||0}/><span className={styles.plus}>и</span><Person p={c.b||{cuid:"",nick:c.partnerName}} smiles={smileCounts[c.partnerName.toLocaleLowerCase("ru")]||0} items={itemCounts[c.partnerName.toLocaleLowerCase("ru")]||0}/></div><p className={styles.since}>{c.since?`Вместе с ${c.since}`:"Дата свадьбы пока не найдена"}</p></article>)}</div>{!couples.length&&<div className={styles.empty}>Семейные пары пока не найдены.</div>}</section></main>;
}
function parseDate(value:string){const m=value.match(/(\d{2})\.(\d{2})\.(\d{4})/);return m?new Date(+m[3],+m[2]-1,+m[1]).getTime():Number.MAX_SAFE_INTEGER;}
function Person({p,smiles,items}:{p:Player;smiles:number;items:number}){return <div className={styles.person}><div className={styles.avatar}>{p.nick.charAt(0).toUpperCase()}</div><div><h2>{p.profileUrl?<a href={p.profileUrl} target="_blank" rel="noreferrer">{p.nick}</a>:p.nick} {p.level?<small>[{p.level}]</small>:null}</h2><p>{p.clanName||"Без клана"}</p><div className={styles.badges}><span>😊 {smiles}</span><Link href={`/personal-items?owner=${encodeURIComponent(p.nick)}`}>⚔️ {items}</Link></div></div></div>}
